//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public int MemberID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public int DesignationID { get; set; }
        public string EmailID { get; set; }
        public string Mobile { get; set; }
        public string Profession { get; set; }
        public System.DateTime TenureFrom { get; set; }
        public System.DateTime TenureTo { get; set; }
        public bool IsDeleted { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual BuildingUnit BuildingUnit { get; set; }
        public virtual KeyValue Designation { get; set; }
    }
}
