//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int TenantID { get; set; }
        public int UnitID { get; set; }
        public int TenantTypeID { get; set; }
        public string TenantName { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string PermanentAddress { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string UDK1 { get; set; }
        public string UDK2 { get; set; }
        public string UDK3 { get; set; }
        public string UDK4 { get; set; }
        public string UDK5 { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual BuildingUnit BuildingUnit { get; set; }
        public virtual KeyValue TenantType { get; set; }
    }
}
