//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDefineField
    {
        public int UDFID { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public bool IsDispaly { get; set; }
        public bool IsActive { get; set; }
        public string FieldLable { get; set; }
        public string ControlType { get; set; }
        public string FieldType { get; set; }
        public string DefaultValue { get; set; }
        public bool IsRequired { get; set; }
        public bool IsRangeValidator { get; set; }
        public string MinimumValue { get; set; }
        public string MaximumValue { get; set; }
        public bool IsRegularExpression { get; set; }
        public string RegularExpression { get; set; }
        public string UserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
